version: "2"
linters:
  enable:
    - tagliatelle
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - tools/cmd/stringer.go
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: backends/internal/providers/
        linters:
          - tagliatelle
      - path: backends/api/internal/payout/handler/v1/createtransaction_test.go
        linters:
          - tagliatelle

  settings:
    staticcheck:
      checks:
        - all
        - -QF1008

    tagliatelle:
      case:
        rules:
          json: camel
          path: camel
          query: camel
          db: snake
          env: upperSnake

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
