all: true
dir: '{{.InterfaceDir}}/mocks'
structname: Mock{{.InterfaceName}}
pkgname: 'mocks'
template: testify
filename: 'mocks.go'
packages:
  autopilot/backends/api/internal:
    config:
      recursive: true
  autopilot/backends/api/pkg/app:
    config:
      recursive: true
  autopilot/backends/internal/core:
    config:
      recursive: true
