#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE identity;
	GRANT ALL PRIVILEGES ON DATABASE identity TO $POSTGRES_USER;

	CREATE DATABASE worker;
	GRANT ALL PRIVILEGES ON DATABASE worker TO $POSTGRES_USER;

	CREATE DATABASE payment_live;
	GRANT ALL PRIVILEGES ON DATABASE payment_live TO $POSTGRES_USER;

	CREATE DATABASE payment_test;
	GRANT ALL PRIVILEGES ON DATABASE payment_live TO $POSTGRES_USER;
EOSQL

