/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/identity/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in to your account */
        post: operations["sign-in"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code?: string;
            errors: components["schemas"]["ErrorDetail"][] | null;
            message: string;
        };
        ErrorDetail: {
            code: string;
            location: string;
            message: string;
            metadata?: components["schemas"]["ValidationMetadata"];
        };
        ValidationMetadata: {
            allowed_values?: string[] | null;
            /** Format: int64 */
            max_length?: number;
            /** Format: double */
            max_value?: number;
            /** Format: int64 */
            min_length?: number;
            /** Format: double */
            min_value?: number;
            regex?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    AccessToken?: string;
                    Email?: string;
                    ID?: string;
                    RefreshToken?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
