// Code generated by "stringer --type=ErrorCode --trimprefix Err"; DO NOT EDIT.

package httpx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrUnknown-1]
	_ = x[ErrUnauthenticated-2]
	_ = x[ErrEntityNotFound-3]
	_ = x[ErrInsufficientPermissions-4]
	_ = x[ErrInvalidBody-1000]
	_ = x[ErrRequired-1001]
	_ = x[ErrInvalidValue-1002]
	_ = x[ErrInvalidDate-1003]
	_ = x[ErrInvalidDateTime-1004]
	_ = x[ErrInvalidTime-1005]
	_ = x[ErrInvalidEmail-1006]
	_ = x[ErrInvalidHostname-1007]
	_ = x[ErrInvalidIPv4-1008]
	_ = x[ErrInvalidIPv6-1009]
	_ = x[ErrInvalidUUID-1010]
	_ = x[ErrMissingLowercase-1011]
	_ = x[ErrMissingUppercase-1012]
	_ = x[ErrMissingNumber-1013]
	_ = x[ErrMissingSpecial-1014]
	_ = x[ErrTooShort-1015]
	_ = x[ErrTooLong-1016]
	_ = x[ErrDuplicateItems-1017]
	_ = x[ErrTooSmall-1018]
	_ = x[ErrTooLarge-1019]
	_ = x[ErrInvalidImageFormat-1020]
	_ = x[ErrInvalidCursor-1021]
	_ = x[ErrInvalidTurnstileToken-1022]
	_ = x[ErrFailedToVerifyTurnstileToken-1023]
	_ = x[ErrInvalidCurrency-1024]
	_ = x[ErrInvalidCountry-1025]
	_ = x[ErrInvalidFinancialAmount-1026]
	_ = x[ErrAccountLocked-10000]
	_ = x[ErrEmailNotVerified-10001]
	_ = x[ErrInvalidCredentials-10002]
	_ = x[ErrInvalidRefreshToken-10003]
	_ = x[ErrInvalidName-10004]
	_ = x[ErrConnectionNotFound-10005]
	_ = x[ErrInvalidConnectionCredentials-10006]
	_ = x[ErrEmailExists-10007]
	_ = x[ErrInvalidOrExpiredToken-10008]
	_ = x[ErrUserNotFound-10009]
	_ = x[ErrInvalidTwoFactorCode-10010]
	_ = x[ErrTwoFactorNotEnabled-10011]
	_ = x[ErrTwoFactorAlreadyEnabled-10012]
	_ = x[ErrTwoFactorPending-10013]
	_ = x[ErrBackupCodeValidation-10014]
	_ = x[ErrTwoFactorLocked-10015]
	_ = x[ErrPaymentNotFound-10016]
	_ = x[ErrUnused-10017]
}

const _ErrorCode_name = "UnknownUnauthenticatedEntityNotFoundInsufficientPermissionsInvalidBodyRequiredInvalidValueInvalidDateInvalidDateTimeInvalidTimeInvalidEmailInvalidHostnameInvalidIPv4InvalidIPv6InvalidUUIDMissingLowercaseMissingUppercaseMissingNumberMissingSpecialTooShortTooLongDuplicateItemsTooSmallTooLargeInvalidImageFormatInvalidCursorInvalidTurnstileTokenFailedToVerifyTurnstileTokenInvalidCurrencyInvalidCountryInvalidFinancialAmountAccountLockedEmailNotVerifiedInvalidCredentialsInvalidRefreshTokenInvalidNameConnectionNotFoundInvalidConnectionCredentialsEmailExistsInvalidOrExpiredTokenUserNotFoundInvalidTwoFactorCodeTwoFactorNotEnabledTwoFactorAlreadyEnabledTwoFactorPendingBackupCodeValidationTwoFactorLockedPaymentNotFoundUnused"

var _ErrorCode_map = map[ErrorCode]string{
	1:     _ErrorCode_name[0:7],
	2:     _ErrorCode_name[7:22],
	3:     _ErrorCode_name[22:36],
	4:     _ErrorCode_name[36:59],
	1000:  _ErrorCode_name[59:70],
	1001:  _ErrorCode_name[70:78],
	1002:  _ErrorCode_name[78:90],
	1003:  _ErrorCode_name[90:101],
	1004:  _ErrorCode_name[101:116],
	1005:  _ErrorCode_name[116:127],
	1006:  _ErrorCode_name[127:139],
	1007:  _ErrorCode_name[139:154],
	1008:  _ErrorCode_name[154:165],
	1009:  _ErrorCode_name[165:176],
	1010:  _ErrorCode_name[176:187],
	1011:  _ErrorCode_name[187:203],
	1012:  _ErrorCode_name[203:219],
	1013:  _ErrorCode_name[219:232],
	1014:  _ErrorCode_name[232:246],
	1015:  _ErrorCode_name[246:254],
	1016:  _ErrorCode_name[254:261],
	1017:  _ErrorCode_name[261:275],
	1018:  _ErrorCode_name[275:283],
	1019:  _ErrorCode_name[283:291],
	1020:  _ErrorCode_name[291:309],
	1021:  _ErrorCode_name[309:322],
	1022:  _ErrorCode_name[322:343],
	1023:  _ErrorCode_name[343:371],
	1024:  _ErrorCode_name[371:386],
	1025:  _ErrorCode_name[386:400],
	1026:  _ErrorCode_name[400:422],
	10000: _ErrorCode_name[422:435],
	10001: _ErrorCode_name[435:451],
	10002: _ErrorCode_name[451:469],
	10003: _ErrorCode_name[469:488],
	10004: _ErrorCode_name[488:499],
	10005: _ErrorCode_name[499:517],
	10006: _ErrorCode_name[517:545],
	10007: _ErrorCode_name[545:556],
	10008: _ErrorCode_name[556:577],
	10009: _ErrorCode_name[577:589],
	10010: _ErrorCode_name[589:609],
	10011: _ErrorCode_name[609:628],
	10012: _ErrorCode_name[628:651],
	10013: _ErrorCode_name[651:667],
	10014: _ErrorCode_name[667:687],
	10015: _ErrorCode_name[687:702],
	10016: _ErrorCode_name[702:717],
	10017: _ErrorCode_name[717:723],
}

func (i ErrorCode) String() string {
	if str, ok := _ErrorCode_map[i]; ok {
		return str
	}
	return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
